---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "system:{{ include "ionoscloud-ccm.name" . }}"
  labels:
    {{- include "ionoscloud-ccm.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  # The node and node lifecycle controllers need all node operations.
  # The service controller watches nodes and lists them on startup.
  # Our provider also requires listing.
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - '*'
  - apiGroups:
    - ""
    resources:
      - nodes/status
    verbs:
      - patch
  # The service controller watches services and lists them on startup.
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - watch
  # Service statuses need be updated when a load balancer IP changed.
  - apiGroups:
      - ""
    resources:
      - services/status
    verbs:
      - update
      - patch
  # Endpoints are used to store which replica's pod became leader.
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - create
      - get
      - update
  # Config maps are used to note explicit load balancer IPs. This is custom behavior of our custom provider.
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - "*"
