---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "system:{{ include "ionoscloud-ccm.name" . }}"
  labels:
    {{- include "ionoscloud-ccm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:{{ include "ionoscloud-ccm.name" . }}"
subjects:
  - kind: ServiceAccount
    name: "{{ include "ionoscloud-ccm.name" . }}"
    namespace: "{{ .Release.Namespace }}"
